"""add formation

Revision ID: 2b33fac8cbc3
Revises: de79e5d9a7b2
Create Date: 2026-04-26 12:24:06.217497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b33fac8cbc3'
down_revision: Union[str, Sequence[str], None] = 'de79e5d9a7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_name'), 'formation', ['name'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_formation_id'), 'chapter', ['formation_id'], unique=False)
    op.create_index(op.f('ix_chapter_name'), 'chapter', ['name'], unique=False)
    op.create_table('video',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_chapter_id'), 'video', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_index(op.f('ix_video_chapter_id'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_chapter_name'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_formation_id'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_formation_name'), table_name='formation')
    op.drop_table('formation')
    # ### end Alembic commands ###
